import { MonsterConfig } from "@/Game/common/types/monsters.types";
import {
  BASE_HEALT,
  FAST,
  NORMAL,
  SLOW,
  VERY_FAST,
  VERY_SLOW,
} from "@/Game/common/constants/monsters.constants";

const WAVE_BASE_HEALT = BASE_HEALT * 131;
const WAVE_BASE_GOLD = 6;
const WAVE_BASE_SPAWN = 9;
const BASE_SPAWN_DURATION = 8000;

export const wave_41_50: MonsterConfig[] = [
  {
    wave_id: 1,
    type: "orcLord",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 2,
    type: "plantFire",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 3,
    type: "slimeVulcan",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    special: {
      spawnsOnDeath: [
        {
          wave_id: 1,
          type: "slimeBoned",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 4,
    type: "plantFire",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 5,
    type: "slimeVulcan",
    size: "huge",
    spawnDuration: BASE_SPAWN_DURATION / 2,
    gold: WAVE_BASE_GOLD * 14,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 30,
    spawnPerSide: 1,
    special: {
      resistToSlow: true,
    },
  },
  {
    wave_id: 6,
    type: "plantFire",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 1.5,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 17,
    type: "slimeVulcan",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 6,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    special: {
      spawnsPerTime: [
        {
          wave_id: 1,
          type: "slimeBoned",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: VERY_FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 8,
    type: "slimeBoned",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 9,
    type: "plantFire",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN + 2,
  },
  {
    wave_id: 10,
    type: "bee",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION * 1.5,
    gold: WAVE_BASE_GOLD + 1,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN,
    air: true,
  },
];
