import { MonsterConfig } from "@/Game/common/types/monsters.types";
import {
  BASE_HEALT,
  FAST,
  NORMAL,
  SLOW,
  VERY_SLOW,
} from "@/Game/common/constants/monsters.constants";

const WAVE_BASE_HEALT = BASE_HEALT * 8;
const WAVE_BASE_GOLD = 2;
const WAVE_BASE_SPAWN = 10;
const BASE_SPAWN_DURATION = 5000;

export const wave_01_10: MonsterConfig[] = [
  {
    wave_id: 1,
    type: "slime",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 2,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 3,
    type: "slime",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    special: {
      spawnsOnDeath: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 4,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 2.5,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 5,
    type: "wolf",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION / 2,
    gold: WAVE_BASE_GOLD * 10,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 13.5,
    spawnPerSide: 1,
  },
  {
    wave_id: 6,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 1.5,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 7,
    type: "slime",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT * 4,
    spawnPerSide: WAVE_BASE_SPAWN,
    special: {
      spawnsPerTime: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 8,
    type: "wolf",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 9,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN + 2,
  },
  {
    wave_id: 10,
    type: "bee",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    air: true,
  },
];
