import { MonsterConfig } from "@/Game/common/types/monsters.types";
import {
  BASE_HEALT,
  FAST,
  NORMAL,
  SLOW,
  VERY_SLOW,
} from "@/Game/common/constants/monsters.constants";

const WAVE_BASE_HEALT = BASE_HEALT * 46;
const WAVE_BASE_GOLD = 5;
const WAVE_BASE_SPAWN = 14;
const BASE_SPAWN_DURATION = 8000;

export const wave_21_30: MonsterConfig[] = [
  {
    wave_id: 21,
    type: "slimeBoned",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 22,
    type: "orc",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 23,
    type: "slime",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN,
    special: {
      spawnsOnDeath: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 24,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 2.5,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 25,
    type: "slimeBoned",
    size: "huge",
    spawnDuration: BASE_SPAWN_DURATION / 2,
    gold: WAVE_BASE_GOLD * 12,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 16,
    spawnPerSide: 1,
    special: {
      spawnsPerTime: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 26,
    type: "slime",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN + 1,
  },
  {
    wave_id: 27,
    type: "slimeBoned",
    size: "huge",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT * 4.5,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    special: {
      spawnsPerTime: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT * 1.5,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 28,
    type: "goblin",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 29,
    type: "orc",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN + 1,
  },
  {
    wave_id: 30,
    type: "bee",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    air: true,
  },
];
