import { MonsterConfig } from "@/Game/common/types/monsters.types";
import {
  BASE_HEALT,
  FAST,
  NORMAL,
  SLOW,
  VERY_FAST,
  VERY_SLOW,
} from "@/Game/common/constants/monsters.constants";

const WAVE_BASE_HEALT = BASE_HEALT * 66;
const WAVE_BASE_GOLD = 5;
const WAVE_BASE_SPAWN = 14;
const BASE_SPAWN_DURATION = 8000;

export const wave_31_40: MonsterConfig[] = [
  {
    wave_id: 1,
    type: "slimeBoned",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT,
    spawnPerSide: WAVE_BASE_SPAWN + 1,
  },
  {
    wave_id: 2,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 3,
    type: "slime",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN,
    special: {
      spawnsOnDeath: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 4,
    type: "orc",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN + 1,
  },
  {
    wave_id: 5,
    type: "orc",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION / 2,
    gold: WAVE_BASE_GOLD * 17,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 18,
    spawnPerSide: 1,
  },
  {
    wave_id: 6,
    type: "slime",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 7,
    type: "slimeBoned",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT * 5,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    special: {
      spawnsPerTime: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT * 1.5,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 8,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 4.5,
    spawnPerSide: WAVE_BASE_SPAWN - 2,
  },
  {
    wave_id: 3,
    type: "slime",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 10,
    type: "bee",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    air: true,
  },
  {
    wave_id: 11,
    type: "slimeBoned",
    size: "huge",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD * 20,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 27,
    spawnPerSide: 1,
    special: {
      resistToSlow: true,
      spawnsPerTime: [
        {
          wave_id: 1,
          type: "slime",
          size: "normal",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: VERY_FAST,
          maxHealth: WAVE_BASE_HEALT * 2,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
];
