import { MonsterConfig } from "@/Game/common/types/monsters.types";
import {
  BASE_HEALT,
  FAST,
  NORMAL,
  SLOW,
  VERY_SLOW,
} from "@/Game/common/constants/monsters.constants";

const WAVE_BASE_HEALT = BASE_HEALT * 25;
const WAVE_BASE_GOLD = 3;
const WAVE_BASE_SPAWN = 12;
const BASE_SPAWN_DURATION = 5000;

export const wave_11_20: MonsterConfig[] = [
  {
    wave_id: 11,
    type: "slimeBoned",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT,
    spawnPerSide: WAVE_BASE_SPAWN + 1,
  },
  {
    wave_id: 12,
    type: "goblin",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 3,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
  },
  {
    wave_id: 3,
    type: "slime",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 2.5,
    spawnPerSide: WAVE_BASE_SPAWN - 1,
    special: {
      spawnsOnDeath: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 2,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 14,
    type: "orc",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: NORMAL,
    maxHealth: WAVE_BASE_HEALT * 2,
    spawnPerSide: WAVE_BASE_SPAWN + 1,
  },
  {
    wave_id: 15,
    type: "goblin",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION / 2,
    gold: WAVE_BASE_GOLD * 13,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 15,
    spawnPerSide: 1,
  },
  {
    wave_id: 17,
    type: "slimeBoned",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT * 4,
    spawnPerSide: WAVE_BASE_SPAWN - 2,
    special: {
      spawnsPerTime: [
        {
          wave_id: 1,
          type: "slime",
          size: "small",
          spawnDuration: BASE_SPAWN_DURATION,
          gold: 1,
          speed: FAST,
          maxHealth: WAVE_BASE_HEALT,
          spawnPerSide: WAVE_BASE_SPAWN,
        },
      ],
    },
  },
  {
    wave_id: 17,
    type: "goblin",
    size: "small",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD,
    speed: VERY_SLOW,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 18,
    type: "wolf",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN - 2,
  },
  {
    wave_id: 19,
    type: "orc",
    size: "normal",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD + 1,
    speed: FAST,
    maxHealth: WAVE_BASE_HEALT * 3.5,
    spawnPerSide: WAVE_BASE_SPAWN,
  },
  {
    wave_id: 20,
    type: "bee",
    size: "big",
    spawnDuration: BASE_SPAWN_DURATION,
    gold: WAVE_BASE_GOLD * 9,
    speed: SLOW,
    maxHealth: WAVE_BASE_HEALT * 8,
    spawnPerSide: 1,
    air: true,
  },
];
